apiVersion: apps/v1
kind: Deployment
metadata:
  name: aravind-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aravind
  template:
    metadata:
      labels:
        app: aravind
    spec:
      containers:
      - name: aravind
        image: aravindkumar0895/aravind:1
        ports:
        - containerPort: 8000
